spring:            #全局配置
  thymeleaf:
    cache: false
  profiles:
    active: dev
  resources:
    static-locations: classpath:static/,file:static/

  sdk:
    alipay:
      dev: true //true沙箱 //false正式
      sign-type: RSA2 //验签方式
      app-id: 2016102600761609
      private-key: //私钥
      alipay-public-key: //支付宝公钥

  mail:
    # 邮件服务地址
    host: smtp.163.com
    # 端口,可不写默认
    port: 465
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: qingjianvip888@163.com
    # 授权码，就是我们刚才准备工作获取的代码
    password: GHTYUYYSTHSTMCKY
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
          auth : true
          starttls:
            enable : false






comment.avatar: /images/avatar.jpg